# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude:
  - vendors

  # Site settings
title: Stovepipe System
author: Etienne Maheu
email: contact@etiennemaheu.com
description: > # this means to ignore newlines until "baseurl:"
  A software developement, architecture and design blog to avoid Stovepipe Systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://stovepipesystem.github.io" # the base hostname & protocol for your site
github_username:  Kawazoe
twitter_username: KawazoeMasahiro
fedi_username: kawazoe
fedi_instance: transfem.social
discord_server: Storepipe Systems
discord_invite: ArfwEhGETD
linkedin_username: etienne-maheu

# Build settings
markdown: kramdown
